### ISSUE TITLE
Reproducible code

### ISSUE THREAD

**Issue by dsblank** [code-Assasin/A_Little_fog_for_a_Large_Turn#1]
Hi! Trying to run your code, but having issues. First, thanks for making your code available! However, it is currently not easily reproducible. Some suggestions/comments:

1. The toplevel README is not clear that there are actually two projects (each with their own README, requirements.txt, etc) Suggest to link to the two lower-level READMEs
2. The READMEs are under-specified. Please expand text like "update the steering model to be attacked and the alpha and theta values. Then come back to the CycleGAN folder". These could be specific instructions: "change X to Y" and "cd cycle_gan_code", etc
3. Your Python packages need to be pinned at specific versions. For example, the current torch requires "pillow<7". In addition, getting another error probably linked to wrong version of scipy:

```
python3 train.py --dataroot /gan_train/ --name model_name --model cycle_gan_fool --preprocess none --batch_size 40 --gpu_ids 0,1,2,3 --norm instance --init_type kaiming --display_port 8097 --no_dropout --lambda_identity 3 --niter_decay 500 --niter 100
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from util.visualizer import Visualizer
  File "/home/dblank/comet/academic/A_Little_fog_for_a_Large_Turn/cycle_gan_code/util/visualizer.py", line 8, in <module>
    from scipy.misc import imresize
ImportError: cannot import name 'imresize'
```  

4. Consider using `pip freeze` to get a list of all of the versions that you used.
5. Also, consider using a automatic logging tool (such as https://comet.ml ) to log the training. It is free (`pip install comet_ml`, get api_key), and with two lines of code can create interactive webpages to explore training and performances. At the top of training file:

```
import comet_ml
experiment = comet_ml.Experiment(api_key="...")
```
Thanks again for sharing!

**Comment by harsmac** [comment]
Sorry for the trouble caused but thank you for taking the time for your suggestions. Let me integrate the same in the next few days.
